# Generated by Django 4.2.2 on 2023-06-19 04:28

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', accounts.models.UserAccountManager()),
            ],
        ),
    ]
