# Generated by Django 4.2.2 on 2023-07-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_publicacion_image_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
