# Generated by Django 4.2.2 on 2023-07-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_publicacion_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/muapp/profile/'),
        ),
    ]
